### Seller POST add new key ###
POST http://localhost:5015/api/key/add
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOTFkODBmNzQ4MWUyMzc1MjdmZTRlNyIsIm5hbWUiOiJ2YW5odW5nbmd1eWVuIiwiaWF0IjoxNjU0NzYyODE5LCJleHAiOjE2NTYwNTg4MTl9.4QMIWmCfeVJ-DFS3tklRldB31lSeTCJns64AVDnKhvU

{
    "key": "key 4",
    "price": "60000",
    "idProduct": 22,
    "idName": 5,
    "seller": "vanhungnguyen",
    "expired": "2022-05-03"
}

### Seller GET all keys 
GET http://localhost:5015/api/key/all
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOTFkODBmNzQ4MWUyMzc1MjdmZTRlNyIsIm5hbWUiOiJ2YW5odW5nbmd1eWVuIiwiaWF0IjoxNjU0NzYyODE5LCJleHAiOjE2NTYwNTg4MTl9.4QMIWmCfeVJ-DFS3tklRldB31lSeTCJns64AVDnKhvU

### Seller PUT update key ###
PUT http://localhost:5015/api/key/update/6295ef0455dc26245d5cdf71
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOTFkODBmNzQ4MWUyMzc1MjdmZTRlNyIsIm5hbWUiOiJ2YW5odW5nbmd1eWVuIiwiaWF0IjoxNjU0NzYyODE5LCJleHAiOjE2NTYwNTg4MTl9.4QMIWmCfeVJ-DFS3tklRldB31lSeTCJns64AVDnKhvU

{
    "key": "key 3",
    "price": 60000,
    "idProduct": 22,
    "idName": 5,
    "seller": "vanhungnguyen",
    "expired": "2022-06-03",
    "note": "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
}

### Seller DELETE key ###
DELETE http://localhost:5015/api/key/delete/6296f08a6917213f224d81d7
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOTFkODBmNzQ4MWUyMzc1MjdmZTRlNyIsIm5hbWUiOiJ2YW5odW5nbmd1eWVuIiwiaWF0IjoxNjU0NzYyODE5LCJleHAiOjE2NTYwNTg4MTl9.4QMIWmCfeVJ-DFS3tklRldB31lSeTCJns64AVDnKhvU

### Seller GET key by id ###
GET http://localhost:5015/api/key/infor/6295ef0455dc26245d5cdf70
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOTFkODBmNzQ4MWUyMzc1MjdmZTRlNyIsIm5hbWUiOiJ2YW5odW5nbmd1eWVuIiwiaWF0IjoxNjU0NzYyODE5LCJleHAiOjE2NTYwNTg4MTl9.4QMIWmCfeVJ-DFS3tklRldB31lSeTCJns64AVDnKhvU

